/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmNotesCreate } from "../funcs/crmNotesCreate.js";
import { crmNotesDelete } from "../funcs/crmNotesDelete.js";
import { crmNotesGet } from "../funcs/crmNotesGet.js";
import { crmNotesList } from "../funcs/crmNotesList.js";
import { crmNotesUpdate } from "../funcs/crmNotesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Notes extends ClientSDK {
  /**
   * Retrieve all CRM notes efficiently.
   *
   * @remarks
   * The `notesAll` operation allows developers to retrieve a comprehensive list of notes from the CRM system. This GET request is essential for accessing detailed note information, which can be used for analysis, reporting, or integration with other systems.
   *
   * Key Parameters:
   * - `x-apideck-consumer-id` (header, required): Identifies the consumer from whom data is being retrieved.
   * - `x-apideck-app-id` (header, required): Specifies the Unify application ID.
   * - `x-apideck-service-id` (header, optional): Indicates the specific service ID to call, useful when multiple integrations are active.
   * - `cursor` (query, optional): Used for pagination to specify the starting point for the next set of results.
   * - `limit` (query, optional): Defines the number of results to return, with a default of 20 and a maximum of 200.
   * - `fields` (query, optional): Allows selection of specific fields to include in the response, enhancing efficiency by reducing payload size.
   *
   * Response Behavior:
   * The operation returns a JSON object containing the requested notes. The response includes metadata for pagination, such as cursors for navigating through pages of results. This operation is crucial for developers needing to access and manipulate CRM note data programmatically.
   */
  async list(
    request: operations.CrmNotesAllRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.CrmNotesAllResponse, { cursor: string }>> {
    return unwrapResultIterator(crmNotesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a new note to the CRM system.
   *
   * @remarks
   * The `notesAdd` operation allows developers to add a new note to the CRM system using a POST request to the `/crm/notes` endpoint. This operation is essential for maintaining detailed records and annotations related to CRM entries. Key parameters include `x-apideck-consumer-id` and `x-apideck-app-id`, which are required headers to identify the consumer and application, respectively. The `x-apideck-service-id` header is optional and used when multiple integrations are active. The operation supports a `raw` query parameter for debugging purposes. Upon successful creation, the API responds with a 201 status code and includes the unique identifier of the newly created note in the response, confirming the addition to the CRM system.
   */
  async create(
    request: operations.CrmNotesAddRequest,
    options?: RequestOptions,
  ): Promise<operations.CrmNotesAddResponse> {
    return unwrapAsync(crmNotesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a specific note by its ID from the CRM system.
   *
   * @remarks
   * The 'notesOne' operation allows developers to retrieve a specific note from the CRM system using its unique identifier. This operation is essential for accessing detailed information about a particular note, which can be used for further processing or display in applications.
   *
   * Key Parameters:
   * - **id** (path): The unique identifier of the note to retrieve. This parameter is required.
   * - **x-apideck-consumer-id** (header): The ID of the consumer from which data is being retrieved. This is a mandatory header.
   * - **x-apideck-app-id** (header): The ID of the Unify application making the request. This is also required.
   * - **x-apideck-service-id** (header): Optional header to specify the service ID when multiple integrations are active.
   * - **raw** (query): Optional parameter to include the raw response, useful for debugging.
   * - **fields** (query): Optional parameter to specify which fields to include in the response, using a comma-separated string.
   *
   * Response Behavior:
   * This operation returns a JSON object representing the note, including all available fields unless specified otherwise by the 'fields' parameter. The response will include a status code of 200 upon successful retrieval.
   */
  async get(
    request: operations.CrmNotesOneRequest,
    options?: RequestOptions,
  ): Promise<operations.CrmNotesOneResponse> {
    return unwrapAsync(crmNotesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing note in the CRM system.
   *
   * @remarks
   * The `notesUpdate` operation allows developers to modify an existing note within the CRM system using a PATCH request to the `/crm/notes/{id}` endpoint. This operation is crucial for maintaining up-to-date information in CRM records.
   *
   * Key Parameters:
   * - `id` (path): The unique identifier of the note to be updated. This is a required parameter.
   * - `x-apideck-consumer-id` (header): Specifies the consumer ID for data retrieval or submission. This is mandatory.
   * - `x-apideck-app-id` (header): Identifies your Unify application. This is a required parameter.
   * - `x-apideck-service-id` (header): Optional parameter to specify the service ID when multiple integrations are active.
   * - `raw` (query): Optional parameter to include the raw response, useful for debugging.
   *
   * Upon successful update, the operation returns a 200 status code along with a JSON object representing the updated note, including its unique identifier. This ensures developers can confirm the update and retrieve the latest note data efficiently.
   */
  async update(
    request: operations.CrmNotesUpdateRequest,
    options?: RequestOptions,
  ): Promise<operations.CrmNotesUpdateResponse> {
    return unwrapAsync(crmNotesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a specific note from the CRM system.
   *
   * @remarks
   * The `notesDelete` operation allows developers to remove a specific note from the CRM system using its unique identifier. This operation is crucial for maintaining up-to-date and relevant data within the CRM by enabling the deletion of outdated or incorrect notes.
   *
   * Key Parameters:
   * - `id` (path parameter, required): The unique identifier of the note to be deleted.
   * - `x-apideck-consumer-id` (header, required): Identifies the consumer from which data is being managed.
   * - `x-apideck-app-id` (header, required): The ID of the Unify application making the request.
   * - `x-apideck-service-id` (header, optional): Specifies the service ID when multiple integrations are active.
   * - `raw` (query parameter, optional): If set, includes the raw response, useful for debugging.
   *
   * Response Behavior: Upon successful deletion, the operation returns a status code of 200, indicating that the note has been successfully removed from the CRM system. No content is returned in the response body.
   */
  async delete(
    request: operations.CrmNotesDeleteRequest,
    options?: RequestOptions,
  ): Promise<operations.CrmNotesDeleteResponse> {
    return unwrapAsync(crmNotesDelete(
      this,
      request,
      options,
    ));
  }
}
