workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CRM API:
        inputs:
            - location: ../../unify/speakeasy-spec.yml
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/crm-api-enhanced
targets:
    apideck:
        target: typescript
        source: CRM API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/crm-enhanced-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
