workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CRM API:
        inputs:
            - location: ../spec-crm-api.enhanced.refs.json
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/crm-api-def
targets:
    apideck:
        target: typescript
        source: CRM API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/crm-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
