/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ContactsUpdateSecurity = {
  apiKey: string;
};

export type ContactsUpdateRequest = {
  /**
   * The unique identifier of the activity record to be deleted. This parameter is essential as it specifies which activity in the CRM system will be removed. Ensure that the ID corresponds to an existing activity to avoid errors.
   */
  id: string;
  /**
   * A unique identifier for the consumer making the request. This ID is crucial for authenticating the consumer and ensuring that the correct data is accessed or modified. It must be a valid consumer ID associated with your account.
   */
  consumerId: string;
  /**
   * The unique identifier of your Unify application. This ID is used to authenticate the application making the request and must match the ID assigned to your application in the Apideck platform.
   */
  appId: string;
  /**
   * An optional parameter used to specify the target service when multiple integrations are active. This ID helps direct the request to the correct service, such as 'pipedrive' or 'salesforce'. It is only necessary if your setup includes multiple services.
   */
  serviceId?: string | undefined;
  /**
   * A boolean flag that, when set to true, includes the raw response in the output. This is primarily used for debugging purposes to provide more detailed information about the response. By default, this is set to false.
   */
  raw?: boolean | undefined;
  contactUpdateRequest: components.ContactUpdateRequest;
};

export type ContactsUpdateResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Contact updated
   */
  contactUpdateResponse?: components.ContactUpdateResponse | undefined;
  /**
   * Unexpected error
   */
  unexpectedErrorResponse?: components.UnexpectedErrorResponse | undefined;
};

/** @internal */
export const ContactsUpdateSecurity$inboundSchema: z.ZodType<
  ContactsUpdateSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string(),
});

/** @internal */
export type ContactsUpdateSecurity$Outbound = {
  apiKey: string;
};

/** @internal */
export const ContactsUpdateSecurity$outboundSchema: z.ZodType<
  ContactsUpdateSecurity$Outbound,
  z.ZodTypeDef,
  ContactsUpdateSecurity
> = z.object({
  apiKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactsUpdateSecurity$ {
  /** @deprecated use `ContactsUpdateSecurity$inboundSchema` instead. */
  export const inboundSchema = ContactsUpdateSecurity$inboundSchema;
  /** @deprecated use `ContactsUpdateSecurity$outboundSchema` instead. */
  export const outboundSchema = ContactsUpdateSecurity$outboundSchema;
  /** @deprecated use `ContactsUpdateSecurity$Outbound` instead. */
  export type Outbound = ContactsUpdateSecurity$Outbound;
}

export function contactsUpdateSecurityToJSON(
  contactsUpdateSecurity: ContactsUpdateSecurity,
): string {
  return JSON.stringify(
    ContactsUpdateSecurity$outboundSchema.parse(contactsUpdateSecurity),
  );
}

export function contactsUpdateSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ContactsUpdateSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactsUpdateSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactsUpdateSecurity' from JSON`,
  );
}

/** @internal */
export const ContactsUpdateRequest$inboundSchema: z.ZodType<
  ContactsUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  consumerId: z.string(),
  appId: z.string(),
  serviceId: z.string().optional(),
  raw: z.boolean().default(false),
  ContactUpdateRequest: components.ContactUpdateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "ContactUpdateRequest": "contactUpdateRequest",
  });
});

/** @internal */
export type ContactsUpdateRequest$Outbound = {
  id: string;
  consumerId: string;
  appId: string;
  serviceId?: string | undefined;
  raw: boolean;
  ContactUpdateRequest: components.ContactUpdateRequest$Outbound;
};

/** @internal */
export const ContactsUpdateRequest$outboundSchema: z.ZodType<
  ContactsUpdateRequest$Outbound,
  z.ZodTypeDef,
  ContactsUpdateRequest
> = z.object({
  id: z.string(),
  consumerId: z.string(),
  appId: z.string(),
  serviceId: z.string().optional(),
  raw: z.boolean().default(false),
  contactUpdateRequest: components.ContactUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    contactUpdateRequest: "ContactUpdateRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactsUpdateRequest$ {
  /** @deprecated use `ContactsUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ContactsUpdateRequest$inboundSchema;
  /** @deprecated use `ContactsUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ContactsUpdateRequest$outboundSchema;
  /** @deprecated use `ContactsUpdateRequest$Outbound` instead. */
  export type Outbound = ContactsUpdateRequest$Outbound;
}

export function contactsUpdateRequestToJSON(
  contactsUpdateRequest: ContactsUpdateRequest,
): string {
  return JSON.stringify(
    ContactsUpdateRequest$outboundSchema.parse(contactsUpdateRequest),
  );
}

export function contactsUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<ContactsUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactsUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactsUpdateRequest' from JSON`,
  );
}

/** @internal */
export const ContactsUpdateResponse$inboundSchema: z.ZodType<
  ContactsUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  ContactUpdateResponse: components.ContactUpdateResponse$inboundSchema
    .optional(),
  UnexpectedErrorResponse: components.UnexpectedErrorResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "ContactUpdateResponse": "contactUpdateResponse",
    "UnexpectedErrorResponse": "unexpectedErrorResponse",
  });
});

/** @internal */
export type ContactsUpdateResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  ContactUpdateResponse?: components.ContactUpdateResponse$Outbound | undefined;
  UnexpectedErrorResponse?:
    | components.UnexpectedErrorResponse$Outbound
    | undefined;
};

/** @internal */
export const ContactsUpdateResponse$outboundSchema: z.ZodType<
  ContactsUpdateResponse$Outbound,
  z.ZodTypeDef,
  ContactsUpdateResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  contactUpdateResponse: components.ContactUpdateResponse$outboundSchema
    .optional(),
  unexpectedErrorResponse: components.UnexpectedErrorResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    contactUpdateResponse: "ContactUpdateResponse",
    unexpectedErrorResponse: "UnexpectedErrorResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactsUpdateResponse$ {
  /** @deprecated use `ContactsUpdateResponse$inboundSchema` instead. */
  export const inboundSchema = ContactsUpdateResponse$inboundSchema;
  /** @deprecated use `ContactsUpdateResponse$outboundSchema` instead. */
  export const outboundSchema = ContactsUpdateResponse$outboundSchema;
  /** @deprecated use `ContactsUpdateResponse$Outbound` instead. */
  export type Outbound = ContactsUpdateResponse$Outbound;
}

export function contactsUpdateResponseToJSON(
  contactsUpdateResponse: ContactsUpdateResponse,
): string {
  return JSON.stringify(
    ContactsUpdateResponse$outboundSchema.parse(contactsUpdateResponse),
  );
}

export function contactsUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContactsUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactsUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactsUpdateResponse' from JSON`,
  );
}
