/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type OpportunitiesFilter = {
  /**
   * Filter opportunities by their title. This allows you to narrow down results to opportunities that match a specific title or keyword.
   */
  title?: string | undefined;
  /**
   * Filter opportunities based on their current status. Useful for retrieving opportunities that are open, closed, or in progress.
   */
  status?: string | undefined;
  /**
   * Filter opportunities by their monetary amount. This helps in focusing on opportunities within a specific budget range.
   */
  monetaryAmount?: number | undefined;
  /**
   * Filter opportunities by their win probability percentage. This is useful for identifying opportunities with a higher likelihood of success.
   */
  winProbability?: number | undefined;
  /**
   * The 'filter.company_id' property is used to filter activities by a specific company ID. This allows you to narrow down the results to activities associated with a particular company.
   */
  companyId?: string | undefined;
  /**
   * The 'filter.owner_id' property is used to filter activities by a specific owner ID, enabling you to view activities managed by a particular owner.
   */
  ownerId?: string | undefined;
  /**
   * Filter opportunities by the primary contact's ID. This allows you to find opportunities associated with a specific contact person.
   */
  primaryContactId?: string | undefined;
};

/** @internal */
export const OpportunitiesFilter$inboundSchema: z.ZodType<
  OpportunitiesFilter,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().optional(),
  status: z.string().optional(),
  monetary_amount: z.number().optional(),
  win_probability: z.number().optional(),
  company_id: z.string().optional(),
  owner_id: z.string().optional(),
  primary_contact_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "monetary_amount": "monetaryAmount",
    "win_probability": "winProbability",
    "company_id": "companyId",
    "owner_id": "ownerId",
    "primary_contact_id": "primaryContactId",
  });
});

/** @internal */
export type OpportunitiesFilter$Outbound = {
  title?: string | undefined;
  status?: string | undefined;
  monetary_amount?: number | undefined;
  win_probability?: number | undefined;
  company_id?: string | undefined;
  owner_id?: string | undefined;
  primary_contact_id?: string | undefined;
};

/** @internal */
export const OpportunitiesFilter$outboundSchema: z.ZodType<
  OpportunitiesFilter$Outbound,
  z.ZodTypeDef,
  OpportunitiesFilter
> = z.object({
  title: z.string().optional(),
  status: z.string().optional(),
  monetaryAmount: z.number().optional(),
  winProbability: z.number().optional(),
  companyId: z.string().optional(),
  ownerId: z.string().optional(),
  primaryContactId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    monetaryAmount: "monetary_amount",
    winProbability: "win_probability",
    companyId: "company_id",
    ownerId: "owner_id",
    primaryContactId: "primary_contact_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OpportunitiesFilter$ {
  /** @deprecated use `OpportunitiesFilter$inboundSchema` instead. */
  export const inboundSchema = OpportunitiesFilter$inboundSchema;
  /** @deprecated use `OpportunitiesFilter$outboundSchema` instead. */
  export const outboundSchema = OpportunitiesFilter$outboundSchema;
  /** @deprecated use `OpportunitiesFilter$Outbound` instead. */
  export type Outbound = OpportunitiesFilter$Outbound;
}

export function opportunitiesFilterToJSON(
  opportunitiesFilter: OpportunitiesFilter,
): string {
  return JSON.stringify(
    OpportunitiesFilter$outboundSchema.parse(opportunitiesFilter),
  );
}

export function opportunitiesFilterFromJSON(
  jsonString: string,
): SafeParseResult<OpportunitiesFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpportunitiesFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpportunitiesFilter' from JSON`,
  );
}
